jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
      displayName: 'Install rust'
    - script: source $HOME/.cargo/env
      displayName: 'Source cargo'
    - script: cargo build
      displayName: 'Build project'
    - script: cargo test --features "test"
      displayName: 'Run tests'