jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
      displayName: 'Install rust'
    - script: |
        source $HOME/.cargo/env
        cargo build
        cargo test --features "test"
